// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

package go_micro_api_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{1}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "go.micro.api.auth.LoginRequest")
	proto.RegisterType((*RegisterRequest)(nil), "go.micro.api.auth.RegisterRequest")
	proto.RegisterType((*Response)(nil), "go.micro.api.auth.Response")
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor_82b5829f48cfb8e5) }

var fileDescriptor_82b5829f48cfb8e5 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xad, 0xee, 0x6a, 0x1d, 0x04, 0x71, 0x50, 0x28, 0xeb, 0x41, 0xc9, 0xc9, 0x53, 0x04,
	0xbd, 0x78, 0xf5, 0xa2, 0x17, 0xbd, 0xe4, 0x0f, 0x48, 0x6c, 0x87, 0x36, 0x60, 0x9b, 0x98, 0x49,
	0xf0, 0xdf, 0xf8, 0x5b, 0xa5, 0x69, 0x2b, 0x56, 0x0b, 0xee, 0x25, 0xe4, 0xf1, 0x86, 0xef, 0x65,
	0x5e, 0xe0, 0xcc, 0x79, 0x1b, 0xec, 0xb5, 0x8e, 0xa1, 0x49, 0x87, 0x4c, 0x1a, 0x4f, 0x6a, 0x2b,
	0x5b, 0x53, 0x7a, 0x2b, 0xb5, 0x33, 0xb2, 0x37, 0xc4, 0x03, 0x1c, 0x3d, 0xd9, 0xda, 0x74, 0x8a,
	0xde, 0x23, 0x71, 0xc0, 0x0d, 0xe4, 0x91, 0xc9, 0x77, 0xba, 0xa5, 0x22, 0xbb, 0xcc, 0xae, 0x0e,
	0xd5, 0xb7, 0xee, 0x3d, 0xa7, 0x99, 0x3f, 0xac, 0xaf, 0x8a, 0xdd, 0xc1, 0x9b, 0xb4, 0x78, 0x81,
	0x63, 0x45, 0xb5, 0xe1, 0x40, 0x7e, 0x1b, 0xd4, 0x29, 0xac, 0xa9, 0xd5, 0xe6, 0x6d, 0xe4, 0x0c,
	0x62, 0x16, 0xb0, 0xf7, 0x2b, 0xe0, 0x0e, 0x72, 0x45, 0xec, 0x6c, 0xc7, 0x84, 0x05, 0x1c, 0x70,
	0x2c, 0x4b, 0x62, 0x4e, 0xe0, 0x5c, 0x4d, 0x12, 0x11, 0x56, 0x95, 0x0e, 0x7a, 0xc4, 0xa6, 0xfb,
	0xcd, 0x67, 0x06, 0xab, 0xfb, 0x18, 0x1a, 0x7c, 0x84, 0x75, 0xda, 0x15, 0x2f, 0xe4, 0x9f, 0x22,
	0xe4, 0xcf, 0x16, 0x36, 0xe7, 0x0b, 0x03, 0x53, 0xba, 0xd8, 0xc1, 0xe7, 0xfe, 0x2d, 0xc3, 0xb2,
	0x28, 0x16, 0x47, 0x67, 0x4d, 0xfc, 0x83, 0x7b, 0xdd, 0x4f, 0xbf, 0x73, 0xfb, 0x15, 0x00, 0x00,
	0xff, 0xff, 0x7e, 0x12, 0xe9, 0x4d, 0xb6, 0x01, 0x00, 0x00,
}
