consul:
  command: -server -bootstrap -rejoin
  image: progrium/consul:latest
  ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
micro:
  image: micro/micro:latest
  command: --registry_address=consul:8500 api --handler=rpc
  links:
    - consul
  ports:
    - "8080:8080"
micro-web:
  image: micro/micro:latest
  command: --registry_address=consul:8500 web
  links:
    - consul
  ports:
    - "8082:8082"
api:
  build: ./auth
  command: --registry_address=consul:8500
  links:
    - consul
users:
  build: ./users
  command: --registry_address=consul:8500
  links:
    - consul

