consul:
  image: bitnami/consul:latest
  hostname: "consul"
  ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
PostgreSQL:
  restart: always
  image: sameersbn/postgresql:10-2
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false
    - DB_USER=admin
    - DB_PASS=admin123
    - DB_NAME=api_micro
  volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
micro:
  image: micro/micro:latest
  command: --registry_address=consul:8500 api
  links:
    - consul
  ports:
    - "8080:8080"
micro-web:
  image: micro/micro:latest
  command: --registry_address=consul:8500 web
  links:
    - consul
  ports:
    - "8082:8082"
auth-gateway:
  container_name: "auth-gateway"
  build: ./auth-gateway
  command: --registry_address=consul:8300
  links:
    - users-service
    - consul
users-gateway:
  container_name: "users-gateway"
  build: ./users-gateway
  command: --registry_address=consul:8300
  links:
    - users-service
    - consul
users-service:
  container_name: "users-service"
  build: ./users-service
  command: --registry_address=consul:8300
  links:
    - PostgreSQL
    - consul
