// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

package go_micro_api_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	users "github.com/lbrulet/GoMicroservices/users-service/proto/users"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{1}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type TokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{2}
}

func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (m *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(m, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

func (m *TokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ClaimsResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClaimsResponse) Reset()         { *m = ClaimsResponse{} }
func (m *ClaimsResponse) String() string { return proto.CompactTextString(m) }
func (*ClaimsResponse) ProtoMessage()    {}
func (*ClaimsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{3}
}

func (m *ClaimsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClaimsResponse.Unmarshal(m, b)
}
func (m *ClaimsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClaimsResponse.Marshal(b, m, deterministic)
}
func (m *ClaimsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimsResponse.Merge(m, src)
}
func (m *ClaimsResponse) XXX_Size() int {
	return xxx_messageInfo_ClaimsResponse.Size(m)
}
func (m *ClaimsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimsResponse proto.InternalMessageInfo

func (m *ClaimsResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LoginResponse struct {
	Token                string      `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Data                 *users.User `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{4}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetData() *users.User {
	if m != nil {
		return m.Data
	}
	return nil
}

type RegisterResponse struct {
	Data                 *users.User `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{5}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetData() *users.User {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "go.micro.api.auth.LoginRequest")
	proto.RegisterType((*RegisterRequest)(nil), "go.micro.api.auth.RegisterRequest")
	proto.RegisterType((*TokenRequest)(nil), "go.micro.api.auth.TokenRequest")
	proto.RegisterType((*ClaimsResponse)(nil), "go.micro.api.auth.ClaimsResponse")
	proto.RegisterType((*LoginResponse)(nil), "go.micro.api.auth.LoginResponse")
	proto.RegisterType((*RegisterResponse)(nil), "go.micro.api.auth.RegisterResponse")
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor_82b5829f48cfb8e5) }

var fileDescriptor_82b5829f48cfb8e5 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x4f, 0xfa, 0x30,
	0x18, 0xc6, 0x61, 0x7f, 0xf6, 0x0f, 0xbe, 0x20, 0x6a, 0x83, 0x09, 0xd9, 0x45, 0xac, 0x1e, 0x3c,
	0x68, 0x97, 0xe0, 0x17, 0xd0, 0x98, 0xa8, 0x07, 0xbc, 0x0c, 0xf1, 0x6a, 0x0a, 0xab, 0xa3, 0x71,
	0xa3, 0xb3, 0xed, 0x30, 0xde, 0xfc, 0xe8, 0x66, 0xed, 0x98, 0x80, 0xd3, 0x70, 0x69, 0xf2, 0xec,
	0x7d, 0xf2, 0xeb, 0xf3, 0xee, 0x29, 0x1c, 0xa6, 0x52, 0x68, 0xe1, 0xd3, 0x4c, 0xcf, 0xcc, 0x41,
	0x8c, 0x46, 0x07, 0x91, 0x20, 0x09, 0x9f, 0x4a, 0x41, 0x68, 0xca, 0x49, 0x3e, 0xf0, 0xee, 0x23,
	0xae, 0x67, 0xd9, 0x84, 0x4c, 0x45, 0xe2, 0xc7, 0x13, 0x99, 0xc5, 0x4c, 0xfb, 0x77, 0xe2, 0x21,
	0x37, 0x29, 0x26, 0x17, 0x7c, 0xca, 0x94, 0x9f, 0x29, 0x26, 0xd5, 0x45, 0x21, 0x7d, 0x8b, 0x36,
	0xdf, 0xec, 0x69, 0xe1, 0xf8, 0x16, 0xda, 0x43, 0x11, 0xf1, 0x79, 0xc0, 0xde, 0x32, 0xa6, 0x34,
	0xf2, 0xa0, 0x99, 0x8f, 0xe7, 0x34, 0x61, 0xbd, 0x7a, 0xbf, 0x7e, 0xb6, 0x13, 0x94, 0x3a, 0x9f,
	0xa5, 0x54, 0xa9, 0x77, 0x21, 0xc3, 0x9e, 0x63, 0x67, 0x4b, 0x8d, 0x9f, 0x61, 0x2f, 0x60, 0x11,
	0x57, 0x9a, 0xc9, 0x6d, 0x50, 0x5d, 0x70, 0x59, 0x42, 0x79, 0x5c, 0x70, 0xac, 0x58, 0xbb, 0xe0,
	0xdf, 0xc6, 0x05, 0xa7, 0xd0, 0x7e, 0x14, 0xaf, 0xac, 0x0c, 0xda, 0x05, 0x57, 0xe7, 0xba, 0x40,
	0x5b, 0x81, 0xfb, 0xd0, 0xb9, 0x89, 0x29, 0x4f, 0x54, 0xc0, 0x54, 0x2a, 0xe6, 0x8a, 0xa1, 0x0e,
	0x38, 0x3c, 0x34, 0x26, 0x37, 0x70, 0x78, 0x88, 0x47, 0xb0, 0x5b, 0x2c, 0x5c, 0x18, 0x2a, 0x41,
	0xe8, 0x1c, 0x1a, 0x21, 0xd5, 0xd4, 0xe4, 0x6b, 0x0d, 0x7a, 0xa4, 0xec, 0x40, 0xc9, 0x05, 0xb1,
	0x3f, 0x70, 0xac, 0x98, 0x0c, 0x8c, 0x0b, 0x5f, 0xc1, 0xfe, 0xf7, 0xf6, 0x05, 0x77, 0x49, 0xa8,
	0x6f, 0x43, 0x18, 0x7c, 0x3a, 0xd0, 0xb8, 0xce, 0xf4, 0x0c, 0x0d, 0xc1, 0x35, 0xf9, 0xd0, 0x11,
	0xf9, 0xd1, 0x3b, 0x59, 0xad, 0xca, 0xeb, 0xff, 0x6e, 0xb0, 0x11, 0x70, 0x0d, 0x8d, 0xa1, 0xb9,
	0x0c, 0x86, 0x70, 0x85, 0x7f, 0xa3, 0x33, 0xef, 0xe4, 0x4f, 0x4f, 0x89, 0x1d, 0x41, 0xeb, 0x89,
	0x49, 0xfe, 0xf2, 0x61, 0x2a, 0xa9, 0x8c, 0xba, 0x5a, 0x96, 0x77, 0x5c, 0x61, 0x58, 0xef, 0x09,
	0xd7, 0x26, 0xff, 0xcd, 0x8b, 0xbc, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x38, 0x8a, 0xc4, 0x69,
	0x07, 0x03, 0x00, 0x00,
}
